name = "C1LinearElasticity"
uuid = "c4af4911-64c2-4139-8d54-5939abe41b5b"
authors = ["Sean McBane <sean.mcbane@protonmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
